### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by davorh** [trustimaging/stride#40]
On a clean account, I installed the latest Miniconda 

Conda 23.3.1 
Python 3.10.10 

Copy pasted line by line

git clone https://github.com/trustimaging/stride
cd stride
conda env create -f environment.yml
conda activate stride
pip install -e .

and tried to run the example:

cd stride_examples/examples/breast2D
mrun python 01_script_forward.py

This is the output:

Traceback (most recent call last):
  File "/home/test/miniconda3/envs/stride/bin/mrun", line 33, in <module>
    sys.exit(load_entry_point('stride', 'console_scripts', 'mrun')())
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/test/stride/mosaic/cli/mrun.py", line 134, in go
    init('monitor', **runtime_config, wait=False)
  File "/home/test/stride/mosaic/__init__.py", line 129, in init
    result = loop.run(_runtime.init, **runtime_config)
  File "/home/test/stride/mosaic/utils/event_loop.py", line 283, in run
    return self._loop.run_until_complete(coro(*args, **kwargs))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/test/stride/mosaic/runtime/monitor.py", line 106, in init
    await super().init(**kwargs)
  File "/home/test/stride/mosaic/runtime/runtime.py", line 202, in init
    self._local_warehouse = SpillBuffer(spill_directory, warehouse_memory)
  File "/home/test/stride/mosaic/utils/spill_buffer.py", line 141, in __init__
    zict.File(spill_directory, mode='w'))
TypeError: File.__init__() got an unexpected keyword argument 'mode'
Exception ignored in: <function ZictBase.__del__ at 0x7f74253e88b0>
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/zict/common.py", line 80, in __del__
    self.close()
  File "/home/test/miniconda3/envs/stride/lib/python3.10/site-packages/zict/buffer.py", line 269, in close
    close(self.fast, self.slow)
AttributeError: 'SpillBuffer' object has no attribute 'fast'

**Comment by Nenad03** [comment]
The problem occurs when the mode parameter is passed to 'zict.File', which is no longer needed.

https://github.com/trustimaging/stride/blob/1c662c94352cd16c9a69c677d917f592b765eabb/mosaic/utils/spill_buffer.py#L139-L141

Changes to the 'zict' package were made with this commit:
https://github.com/dask/zict/commit/c61ad646ae874561282bf173065ab9b96935ed45
