### ISSUE TITLE
Unable to install stride

### ISSUE THREAD

**Issue by elcolie** [trustimaging/stride#68]
I am trying install on M2 OSX 14.1.1
Step to reproduce:
1. `conda env create -f environment.yml`
1. `conda activate stride`
1. `pip install -e .`
Errors:
```bash
❯ pip install .
Processing /Users/sarit/study/stride
  Preparing metadata (setup.py) ... done
Collecting blosc (from stride==1.2)
  Downloading blosc-1.11.1.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/sarit/anaconda3/envs/stride/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sarit/anaconda3/envs/stride/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sarit/anaconda3/envs/stride/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h5/4mllfnsj3_z7pn72_yfp82qw0000gn/T/pip-build-env-nld0hmmi/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h5/4mllfnsj3_z7pn72_yfp82qw0000gn/T/pip-build-env-nld0hmmi/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/h5/4mllfnsj3_z7pn72_yfp82qw0000gn/T/pip-build-env-nld0hmmi/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/h5/4mllfnsj3_z7pn72_yfp82qw0000gn/T/pip-build-env-nld0hmmi/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 84, in <module>
      KeyError: 'flags'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ccuetom** [comment]
This seems to be an issue with the new Python 3.12. Until we fix it, I would recommend that you create your environment with Python 3.11
